### ISSUE TITLE
CSU requires bibliography in the table of contents

### ISSUE THREAD

**Issue by lukelbd** [idfah/csuthesis#10]
CSU requires the bibliography in the table of contents, which this template does not seem to do. Adding the following to the preamble seems to fix this problem, with no apparent side-effects:

```
\usepackage[nottoc]{tocbibind}
```

(P.S. Thank you for publishing this repo! It was a lifesaver.)

**Comment by lukelbd** [comment]
Scratch that: the above messes up the "List of Figures" and "List of Tables" frontmatter header styling, for some reason. This is the safer solution:

```
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{Bibliography}
\bibliographystyle{style}
\bibliography{file}
```

From [this stackexchange thread](https://tex.stackexchange.com/a/98995/73149).

**Comment by idfah** [comment]
Thank you for the report @lukelbd   The bibliography is now included in the TOC in the latest version of the template.
