### ISSUE TITLE
citation ordering in text

### ISSUE THREAD

**Issue by henryrscharf** [idfah/csuthesis#2]
I had some trouble getting my citations to appear in the order I wrote them when citing multiple works in the text. For example, \citep[e.g.,][]{Smithers2013, Simpson2014} should have yielded (Smithers, 2013; Simpson, 2014) in the text, but instead I was getting the alphabetical ordering (Simpson, 2014; Smithers, 2013), despite my bibliography style file. 

I ultimately concluded that the problem arose due to a "conflict" between the natbib and cite packages. If other authors are using natbib and having similar problems, they may wish to comment out line 318: "\RequirePackage{cite}".

Hope this helps others! Apologies if this is not the venue for reporting this sort of thing, just trying to be helpful.

Henry Scharf,
Statistics

**Comment by idfah** [comment]
@henryrscharf Thanks for the report!  Was removing the \RequirePackage{cite} all that you needed to do to fix your problem?  If so, I might just move this and the shortcuts below it to the sample.tex instead.  Then people can take or leave it without having to modify the style file.

**Comment by henryrscharf** [comment]
Yep, that's all. I think shifting it those lines to the sample.tex makes sense.

**Comment by idfah** [comment]
I have moved the `\RequirePackage{cite}` to `sample.tex` to make this optional.  Users can replace with natbib there if they wish.

Going to close this, thank you @henryrscharf for the report!

**Comment by GuruMulay** [comment]
I am having an issue remotely similar to this. The citations in my output pdf are not in the same order as what they are written in .bib file. 
With and without commenting \RequirePackage{cite}, I tried following solutions but they don't seem to be working: 
https://stackoverflow.com/questions/144639/how-to-order-citations-by-appearance-using-bibtex

I am quite sure I am missing something basic. I will really appreciate any suggestions. Thank you.
