### ISSUE TITLE
Bibliography not showing up in TOC

### ISSUE THREAD

**Issue by mandilin** [idfah/csuthesis#6]
For some reason my References section is not showing up in the table of contents. Any idea why this might be and how to fix it?

Note that per the previous issue, I have commented out \RequirePackage{cite} in thesis.cls. 
I also added this to my main TeX document:
\usepackage[natbibapa]{apacite}
\bibliographystyle{apalike}

**Comment by idfah** [comment]
@mandilin Does it work if you remove the `[natbibapa]` option?  It is not currently designed to work with natbib.  If it still doesn't work, do you have any warnings when building your tex file?

Also, you could try
```
\bibliographystyle{apacite}
```

or
```
\bibliographystyle{apa}
```

Do either of those styles work?

**Comment by idfah** [comment]
Here is a pull request with an example that works for me:
https://github.com/idfah/csuthesis/pull/7/files

If this works for you I will merge it in.

I don't know why I can't get the `apalike` style to work for me?  I will look into this more.

**Comment by clint-leach** [comment]
If all else fails, you could also just try to do it manually with:
```
\addcontentsline{toc}{chapter}{Bibliography}
```

**Comment by idfah** [comment]
^^^ yep. `thesis.cls` attempts to add this line for you but may not be able to do this for all citation packages.

**Comment by mandilin** [comment]
Thanks everyone! I went with the solution from @clint-leach because I am using a lot of \citep's and such.
