### ISSUE TITLE
Add footnote to chapter title?

### ISSUE THREAD

**Issue by mandilin** [idfah/csuthesis#8]
According to the dissertation formatting guide,
"Any references to journal publications, authors, etc. on your chapter pages or major heading
pages should be listed as a footnote."

Is there a way to add a footnote at the end of a chapter title? I tried something like \chapter{chapter title \footnote{my footnote}} but it wouldn't compile.

Thanks!

**Comment by Optimus-Pine** [comment]
Sorry if this is a little late and you've already found a solution! I was able to substitute the line, 
`\chapter[Introduction]{Introduction\footnote{Citation}}`
for 
`\chapter{Introduction}`
in `sample.tex` and the result compiled as expected.

I hope this helps!

**Comment by mandilin** [comment]
Amazing! Thank you!!
